# Generated by Django 6.0.2 on 2026-02-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
